workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK (Release)
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - basma@example.com   # ← اكتبي إيميلك هنا عشان يوصلك APK بعد كل Build
