platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
