platform :ios, '12.0'

# Prevent Cocoapods from embedding multiple copies of the same library
use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
